== Kartlegging med geodetiske metoder

=== Innledning

Geodetiske metoder benyttes til kartlegging ved høye krav til nøyaktighet eller når forholdene ellers gjør det naturlig, for eksempel ved mindre ajourføringer eller ved måling i områder som ikke kan kartlegges fotogrammetrisk på grunn av dårlig innsyn.

// Standarden <<SAT>> gir anbefalinger om hvordan posisjonsbestemmelse med satellitter bør utføres i kart- og oppmålingsarbeider.


=== Referanserammer og transformasjoner


====
[#krav-landmaling-referanserammer-transformasjoner,reftext="Krav landmåling referanserammer og transformasjoner"]
*KRAV LANDMÅLING REFERANSERAMMER OG TRANSFORMASJONER*

* Produksjonen av produktene beskrevet i denne standarden skal anvende Kartverkets offisielle transformasjonsformler. Se også kapittel "6.5 Omforming av koordinater" i <<GG>>.
* Det skal kun benyttes referanserammer som ivaretar sluttproduktets nøyaktighetskrav i hele produksjonskjeden. Dersom dette ikke er mulig så må dette avtales.
====


=== Målemetoder

Geodetisk kartlegging foregår enten med satellittbaserte metoder eller ved bruk av totalstasjon.

==== Satellittbaserte metoder (GNSS)

Satellittbasert måling baseres på ulike typer utstyr og satellittsystemer. Målingene kan utføres som sanntidsmåling eller med posisjonsberegning i ettertid.  

===== Sanntidsmåling
Den mest aktuelle metoden for posisjonsbestemmelse i sanntid er RTK. I RTK overføres korreksjonsdata til satellittmottakeren (roveren) fra en referansestasjon i et kjent punkt. En variant av RTK er nettverks-RTK hvor korreksjonsdataene kommer fra en virtuell referansestasjon (VRS), beregnet fra et nett av faste stasjoner og overføres til satellittmottakeren fra et sentralt kontrollsenter. Både private firma og Statens kartverk tilbyr sanntidstjenester basert på nettverks-RTK. 

====
[#krav-landmaling-sanntidsmaling,reftext="Krav landmåling sanntidsmåling"]
*KRAV LANDMÅLING SANNTIDSMÅLING*

* For kontroll skal minimum ett fastmerke (kontrollpunkt) med tilfredsstillende kvalitet registreres før og etter innmåling.
* Under målingen skal en også oppsøke andre fastmerker. Dersom det ikke finnes lett tilgjengelige fastmerker, kan en kontrollere mot tidligere bestemte objekttyper av god kvalitet og som er godt definert, for eksempel kummer. Avvikene skal ikke overstige 1/3 av kravet til stedfestingsnøyaktighet for de mest nøyaktige objekttypene som skal innmåles. Avvikene skal dokumenteres.
* Ved bytte av referansestasjon, skal minst en godt definert objekttype fra forrige oppstilling innmåles på nytt for kontroll. Avvikene skal dokumenteres.
====


RTK kan benyttes med VRS eller egen referansestasjon. Referansestasjonen settes opp over et fastmerke med kjent kvalitet, nærmere enn 5-10 km fra måleområdet.

// Når det gjelder den praktiske gjennomføringen av målearbeidene og kravene til disse, vises det til standarden <<SAT>>.

===== Transformasjoner
Ved differensielle satellittbaserte metoder fremkommer ellipsoidiske høydeforskjeller. For å sikre leveranse i NN2000 med gjeldene høydereferansemodell, må høydeforskjellene korrigeres. Dette kan gjøres på flere måter:

* Korrigerte høydeforskjeller kan utledes fra transformasjonspunkt der både ellipsoidisk og ortometrisk høyde (NN2000) er kjent, og der referansestasjonen er et av transformasjonspunktene.

* Korrigerte høydeforskjeller kan utledes fra en eksisterende høydereferansemodell. 

// (se standarden "Norges offisielle høydesystem og referansenivåer").

// For videre beskrivelse av transformasjon se standardene <<SAT>> og https://www.kartverket.no/globalassets/geodataarbeid/standardisering/standarder/standarder-geografisk-informasjon/koordinatbaserte-referansesystemer-2.1-standarder-geografisk-informasjon.pdf[Koordinatbaserte referansesystemer, 2.1 2009].
For videre beskrivelse av transformasjon se standarden <<GG>>.


==== Bruk av totalstasjon
Stasjonspunkter kan være et fastmerke eller et punkt som bestemmes med kontroll, for eksempel ved fri oppstilling. Ved fri oppstilling skal en måle retning, avstand og vertikalvinkel mot minimum to fastmerker.
	
Stasjonspunkter og orienteringspunkter skal fortrinnsvis være fastmerker i Stamnettet, Landsnettet eller det kommunale nettet (gjelder for kommuner), eller egenetablerte fastmerker etablert med GNSS med tilstrekkelig kvalitet. Slike punkter dokumenteres ved beregning av ytre pålitelighet i programvare som håndterer dette. Påliteligheten må tilfredsstille de krav som stilles i standarden <<GG>> for den aktuelle områdetypen.

====
[#krav-landmaling-innmaling-med-totalstasjon,reftext="Krav landmåling innmåling med totalstasjon"]
*KRAV LANDMÅLING INNMÅLING MED TOTALSTASJON*

For å sikre seg så godt som mulig mot grove feil må det settes krav til innmålingen av objekttyper: 

* Det skal leses av mot samme orienteringspunkt først og sist i oppstillingen. +
* Det skal om mulig benyttes minst to orienteringssikt i hver oppstilling. +
* Ved ny oppstilling skal minst en godt definert objekttype fra forrige oppstilling innmåles på nytt for kontroll. +
* Ved fri oppstilling skal standardavviket på bestemmelsen av oppstillingspunktet ikke overstige 1/3 av kravene til de mest nøyaktige objekttypene som skal innmåles. +
* Innmåling av objekttyper skal bare unntaksvis gjøres med større avstander enn 500 m. Avstandene må ikke i noe tilfelle overstige avstanden til orienteringspunktene. Refraksjonsforholdene kan være avgjørende for høydenøyaktigheten. I noen tilfeller vil det innebære at avstandene må være kortere.
====

Innmåling av kartobjekter ved bruk av totalstasjon kan utføres i en kikkertstilling dersom instrumentleverandørens anbefalte kalibreringsprosedyrer av instrumentet er foretatt. Utførte kalibreringer skal dokumenteres.


=== Måleinstrumenter

Oppdragstaker er ansvarlig for å bruke instrumenter, materiell og måleopplegg som gir tilfredsstillende resultater i forhold til oppgavene. Det skal fortrinnsvis utføres årlig service på benyttede måleinstrumenter.

////	
Aktuelle dokumenter:

* Standarden <<GN>>, kapittel 6 Kontroll og kalibrering av måleutstyr.
* Standarden https://www.kartverket.no/globalassets/geodataarbeid/standardisering/standarder/standarder-geografisk-informasjon/kontroll-og-kalibrering-av-elektrooptiske-avstandsmalere-2.1-standarder-geografisk-informasjon.pdf[Kontroll og kalibrering av elektrooptiske avstandsmålere 2.1 2009].
* Standarden <<SAT>>.

////

Oppdragstakeren skal i sin rapport dokumentere at instrumentene som blir brukt, minst har den nøyaktigheten som kreves for å tilfredsstille kravene til sluttproduktet. En slik dokumentasjon gis for hvert benyttet instrument. Fabrikkmerke, type og serienummer oppgis. 

// Det vises til Instrument-levnetsoversikten i Tillegg B i standarden <<GN>>.


=== Beregning
Oppdragstaker er ansvarlig for at valg av måleopplegg, programvare og beregningsopplegg gir god nok nøyaktighet i forhold til kravene.

// Ved bruk av satellittutstyr er beregning beskrevet i standarden <<SAT>>.

=== Egenkontroll og rapportering (geodetisk kartlegging)
Det skal leveres en rapport for den geodetiske kartleggingen, med leveransene som vedlegg til rapporten. Generelt gjelder at alle resultat fra beregninger skal vurderes og kommenteres. Eventuelle problemer i prosjektet skal omtales spesielt. Rapporten er en del av leveransen og skal leveres samtidig med det produktet som rapporten omhandler. 

:xrefstyle: short

====
[#krav-landmaling-rapportering-geodetisk-kartlegging,reftext="Krav landmåling rapportering - geodetisk kartlegging"]
*KRAV LANDMÅLING RAPPORTERING - GEODETISK KARTLEGGING*

* Rapport for geodetisk kartlegging skal som minimum inneholde informasjonen spesifisert i <<tab-rapp-geodetisk-kartlegging>>.


:xrefstyle: full

[[tab-rapp-geodetisk-kartlegging]]
.Rapport for geodetisk kartlegging
[cols="3*",options="header"]
|===
|Kategori|Element|Innhold
.6+|Generell informasjon|Oppdragsgiver|(adresse og prosjektleder)
|Oppdragets navn og nummer|(LACHFFXX)
|Oppdragstaker|(adresse, prosjektleder, fagansvarlig og underleverandører)
|Beskrivelse av oppdraget|(kontraktsarbeid, areal, standard)
|Antall eksemplar av rapport|(antall og oppbevaringssted)
|Datering og signatur|(dd.mm.åååå, signatur)
.11+|Geodetisk kartlegging|Utførelse av målearbeidene|(navn, tidspunkt, beskrivelse av eventuelle vanskeligheter)
|Benyttet måleutstyr|(merke, type, nummer)
|Dokumentasjon|(kalibreringssertifikat)
|Geodetisk og vertikalt grunnlag|(geodetisk datum, vertikalt datum, ellipsoidisk/ortometrisk høyde, kartprojeksjon, akse/sone)
|Benyttede grunnlagspunkter|(navn, nummer, dokumentasjon av kvalitet)
|Målemetode og -prosedyre|Valgt målemetode og -prosedyre skal begrunnes
|HREF|Versjon av HREF benyttet under datafangst
|Innmålte objekttyper|Liste over alle objekter
|Produktspesifikasjon, objektkatalog og topologisk nivå|(versjon)
|Egenkontroll|Avvik ved kontrollmåling av objekter innmålt fra flere stasjoner, samt kontroll av tidligere kartlagte objekter
|Dataleveranse|Spesifikasjon av leveranseformat og eventuell inndeling i filer
.4+|Vedlegg|Observasjoner|Sortert utlisting av observasjonene på digital form
|Beregninger|Beregningsresultatet på digital form
|Transformasjon|Resultat av eventuelle grovefeilsøk, transformasjonsparametere og restfeil i transformasjonspunktene, avvik i kontrollpunktene skal dokumenteres
|Innmålte objekter|Innmålte objekter på avtalt vektorformat
|===

====